# Generated by Django 3.0.4 on 2020-03-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200330_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='refund_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
